{"name": "test_verify_login_with_invalid_username", "status": "passed", "start": 1722047892553, "stop": 1722047892941, "uuid": "3f5e2a17-ad2e-4cfd-becd-3b9550f9c152", "historyId": "f5d1e6bc02260ccd5e4bd47a47c4a927", "testCaseId": "f5d1e6bc02260ccd5e4bd47a47c4a927", "fullName": "test.test_Login.TestLogin#test_verify_login_with_invalid_username", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Raunak"}, {"name": "thread", "value": "10708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_Login"}]}